### ISSUE TITLE
Clickable PanelResizeHandle 

### ISSUE THREAD

**Issue by erickjth** [bvaughn/react-resizable-panels#101]
Hey there,
I have a use case where the PanelResizeHandle needs to be clickable, so on clicking it opens/closes depending of the current state. Is there a clean way to do this? I tried using a full clickable box, but when the dragging ends the click action is performed, and I would like to have these two events isolated.
Thanks!

**Comment by bvaughn** [comment]
@erickjth You could do this by adding an `onClick` handler to whatever view you render inside of the `PanelResizeHandle`.

As you mentioned, you'll need to _prevent_ clicks from being handled if the user drags to resize though. I'd suggest capturing the time of the "mousedown" event and comparing on the "mouseup" event so that you can ignore fake "clicks" (when there's more than a few ms between).

This isn't something I want to add to the library as built-in functionality but you should have all of the pieces you need with the [imperative API methods](https://react-resizable-panels.vercel.app/examples/imperative-api). If you run into a snag, shared a Code Sandbox with me and I'll take a look!
