### ISSUE TITLE
Weird resize behavior when ResizeHandle placed on only one size of a panel

### ISSUE THREAD

**Issue by mohsinulhaq** [bvaughn/react-resizable-panels#124]
Ref: https://codesandbox.io/s/react-resizable-panels-forked-krrms8?file=/src/App.js

I expect only the middle and the right panel to be resized. But instead, the left panel is affected.

**Comment by bvaughn** [comment]
There's a relationship between the number and position of panels and resize handles. (If there are N panels, there should be N-1 resize handles– and they should be interleaved.)

What the sandbox you linked shows is that the first resize handle gets assigned to panels 1/2, and since there isn't a 2nd resize handle– nothing gets assigned to panels 2/3. Ideally we would warn about this (maybe as part of #65) but I would consider this a bad/unsupported panel group configuration.

I can't think of a use case for using three resizable panel components with only one handle. I think what you really want is something more like this:
https://codesandbox.io/s/react-resizable-panels-forked-dlogu6

**Comment by bvaughn** [comment]
This library's primary (only?) use case is _resizable_ panels. If you want to render a non-resizable "panel" – then just don't wrap it in a `<Panel>` (like my Code Sandbox shows).

**Comment by mohsinulhaq** [comment]
I was imagining a feature where there is a "primary" content panel that will not be resizable as it contains the main content.
And there could be many "secondary" panels around it that could be freely resized.

Something like this: https://codesandbox.io/s/react-resizable-panels-forked-krrms8?file=/src/App.js

**Comment by bvaughn** [comment]
You can build that kind of app– just don't wrap the "primary" content in a `<Panel>` if it's not resizable :)

**Comment by mohsinulhaq** [comment]
https://codesandbox.io/s/react-resizable-panels-forked-krrms8?file=/src/App.js
It still works the same way. Am I doing it wrong?

**Comment by mohsinulhaq** [comment]
Oh, I see. Of course! Thanks for taking the time to edit the demo.
This is definitely a cleaner solution!
