### ISSUE TITLE
Bolierplate code not working on new React project

### ISSUE THREAD

**Issue by robertgregg3** [bvaughn/react-resizable-panels#165]
I was testing out react-resizable-panels on my project and couldn't get the resizable panels to show.  I thought it could be to do with some dependencies I had installed but then just tried it again on a brand new react project:

1. npx create-react-app .
2. yarn install
3. yarn add react-resizable-panels
4. add code found here: https://react-resizable-panels.vercel.app/examples/horizontal
5. yarn start
6. result:

![image](https://github.com/bvaughn/react-resizable-panels/assets/4264701/f6f78be6-1645-461a-bcde-caefc56f8042)

**Comment by robertgregg3** [comment]
The html is not rendering the same html as the demo examples:

![image](https://github.com/bvaughn/react-resizable-panels/assets/4264701/0d80f975-fc7a-4a87-b3da-630786b3a9b9)

**Comment by bvaughn** [comment]
From what I can tell, the "code" is working. You just haven't added any styling to your panels.

This library doesn't provide a default visual style for panels because that's a huge problem space. It just provides the functionality of resizing. If you want to copy the visual styles from the demo website though, you can find them here

https://github.com/bvaughn/react-resizable-panels/blob/main/packages/react-resizable-panels-website/src/routes/examples/shared.module.css
