### ISSUE TITLE
Collapse function in imperative API doesn't work when units are set to pixels

### ISSUE THREAD

**Issue by leytonblackler** [bvaughn/react-resizable-panels#194]
Hey there,

I've been really enjoying using this library, thanks for building it!

In my use case, I'm using pixels as the units and have set this via the `units` prop on `PanelGroup`. I've run into an issue where a panel won't collapse when I call the `collapse` function via the ref set on the panel. Instead, the panel actually increases in size. I've made sure that the `collapsible` and `collapsedSize` props have been set on the panel I'm controlling and the panel is definitely not already collapsed when I try to collapse it. In this example, the collapsed size of panel is `72px`.

I've done some debugging though and I think I've found what's causing it. I added a breakpoint to the `collapsePanel` callback in the `PanelGroup` component and it looks like it's attempting to compare the percentage units of `currentSize` with the pixel units of `collapsedSize`.

Here's a screenshot of the breakpoint and the values during runtime:
![Screenshot 2023-09-20 at 3 16 00 PM](https://github.com/bvaughn/react-resizable-panels/assets/18431950/69bae001-4d93-4fae-b538-3105bfc1edca)

So I'm guessing that because of the unit mismatch, it might be attempting to set the width of the panel to `72%` rather than the collapsed size of `72px`?

Hopefully this helps - I can try provide further info if needed though.

**Comment by bvaughn** [comment]
Hey @leytonblackler. Thanks for doing some investigatory work here.

There are a few issues with the pixels release (e.g. #180, #181) and this one– all of which I'm trying to address with PR #182, but I'm only working on it now and then because this is a side project.

I'm probably at the point where I'd accept a PR that fixed issues like the one you're reporting, and publish an intermediate release, so if you'd like to post one– that's an option. Otherwise though I think it will have to wait until I finish #182.

**Comment by bvaughn** [comment]
#182 has been merged and I plan to release v56 this afternoon with the changes. I'm closing old issues in light of the rewrite because most of them are no longer relevant. If this issue still occurs with v56, please re-open with an updated description on how to reproduce it.
