### ISSUE TITLE
Drag gets priority over overlapping elements

### ISSUE THREAD

**Issue by vanquishkuso** [bvaughn/react-resizable-panels#296]
Hi, thank you for an awesome package!

I have an issue that I thought was similar to #288 but it doesn't seem to be fixed with the latest version 2.0.7. I have an overlapping button element that I want to be able to click and collapse a drawer. However, the draggable border gets priority even though the Z-index on the button is above.

This can be partially solved by moving the button outside of the resizable components (although it makes the positioning of the button troublesome), but when the button contains only an icon and not text, the drag gets priority again. The button is although still clickable.

If the button contains text **and** is outside of the resizable components it works as expected, but the positioning of the button is again cumbersome.

It's difficult to explain, so I reproduced a simple example it in the sandbox below:
[https://codesandbox.io/p/sandbox/react-resizable-panels-forked-s5jzpg](https://codesandbox.io/p/sandbox/react-resizable-panels-forked-s5jzpg)

**Comment by bvaughn** [comment]
The behavior you're describing is controlled by this logic:

https://github.com/bvaughn/react-resizable-panels/blob/cd32d1c3d7c57bbb1f6430812aff7f0d75ee1d13/packages/react-resizable-panels/src/PanelResizeHandleRegistry.ts#L168-L204

This Replay shows what's happening: [8c5e2948-00d4-4dd0-a7f7-c11f660ee59f](https://app.replay.io/recording/bvaughnreact-resizable-panelsissues296--8c5e2948-00d4-4dd0-a7f7-c11f660ee59f)

Nearest I can tell, it looks like a bug in the [`stacking-order`](https://npmjs.com/package/stacking-order) package, because it's returning a value indicating that your buttons are not "above" the drag-handle. I added a comment where I Think that library is broken, but I don't have time to dig into it more.

You _could_ try reducing this test case even more and filing an issue in that project's GitHub? Or if you'd like to dig in yourself and submit a PR I'll try to find time to review it. I'm pretty swamped right now though with work and don't have time to dig into this more.

**Comment by vanquishkuso** [comment]
Thank you for the reply, I'll see what I kind find in that repo, in the meantime I'll try to use a workaround though.

**Comment by bvaughn** [comment]
I had a few minutes this morning, and tried reproducing this in an isolated project. For some reason, I was unable to reproduce the behavior. I wonder what it is about the Code Sandbox you attached that is different...

**Comment by bvaughn** [comment]
Ah, I think it's somehow being caused by the flex layout! That is promising.

**Comment by bvaughn** [comment]
I had a few minutes this morning so I made a smaller repro and filed https://github.com/Rich-Harris/stacking-order/issues/3

**Comment by vanquishkuso** [comment]
Wow thank you so much for taking the time to look at it! Very glad the problem could be located. Looking forward to their response and hopefully a fix since my workaround wasn't so good 😊.

**Comment by bvaughn** [comment]
No problem! Think I found a fix @ https://github.com/Rich-Harris/stacking-order/pull/4

**Comment by bvaughn** [comment]
Fixed published in 2.0.9

---

❤️ → ☕ [givebrian.coffee](http://givebrian.coffee/)

**Comment by vanquishkuso** [comment]
Amazing, thanks!
