### ISSUE TITLE
export 'useId' was not found in 'react'

### ISSUE THREAD

**Issue by nwidger** [bvaughn/react-resizable-panels#381]
Projects using this package and building with React <18 (the `useId` hook was introduced in React 18) and `esbuild` v0.19.6 or new (v0.23.0 is the latest version) see an error similar to the following:

```
export 'useId' (imported as 'Du') was not found in 'react' (possible exports: Children, Component, Fragment, Profiler, PureComponent, StrictMode, Suspense, __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED, cloneElement, createContext, createElement, createFactory, createRef, forwardRef, isValidElement, lazy, memo, useCallback, useContext, useDebugValue, useEffect, useImperativeHandle, useLayoutEffect, useMemo, useReducer, useRef, useState, version)
```

It seems like starting with `esbuild` v0.19.6, the line [here](https://github.com/bvaughn/react-resizable-panels/blob/main/packages/react-resizable-panels/src/vendor/react.ts#L40C1-L40C66) is minified from:

```typescript
const useId = (React as any)["useId".toString()] as () => string;
```

to just:

```typescript
const useId = React.useId;
```

and therefore is no longer sufficiently obfuscated. I believe this issue similar in nature to #82.  It appears [other projects facing similar issues](https://github.com/mui/material-ui/issues/41190#issuecomment-2040873379) have further obfuscated the reference to `React.useId` to:

```typescript
const useId = (React as any)[`useId${Math.random()}`.slice(0, 5)] as () => string;
```

You can see this in action using the `esbuild` playground link below.  Using the Version pulldown in the top-right you can see how the old version was sufficiently obfuscated up until `esbuild` v0.19.6, where `esbuild` apparently became smart enough to minify it to just `React.useId`.

https://esbuild.github.io/try/#dAAwLjIzLjAALS1taW5pZnkALy8gY3VycmVudCB2ZXJzaW9uLCBtaW5pZmllcyB0byAiUmVhY3QudXNlSWQiClJlYWN0WyJ1c2VJZCIudG9TdHJpbmcoKV07CgovLyBwcm9wb3NlZCB2ZXJzaW9uLCBtaW5pZmllcyB0byAiUmVhY3RbYHVzZUlkJHtNYXRoLnJhbmRvbSgpfWAuc2xpY2UoMCw1KV0iClJlYWN0W2B1c2VJZCR7TWF0aC5yYW5kb20oKX1gLnNsaWNlKDAsIDUpXTs

Would you be opposed to further obfuscating this line using the `Math.random()` technique above?  If so I would be happy to open a PR with the change.  Thanks!

**Comment by bvaughn** [comment]
Yeah, please do submit a PR and I'll be happy to review it!

**Comment by nwidger** [comment]
@bvaughn Awesome, thanks!  I've just opened https://github.com/bvaughn/react-resizable-panels/pull/382.

**Comment by bvaughn** [comment]
Fix published in v2.0.23 
---

❤️ → ☕ [givebrian.coffee](http://givebrian.coffee/)

**Comment by nwidger** [comment]
@bvaughn Thanks you so much, I really appreciate it!

**Comment by chrisb2244** [comment]
A potential issue caused by this type of workaround is now being raised by the `dynamicIO` mechanisms with Next.js - if I understand correctly, they've [overridden Math.random](https://github.com/vercel/next.js/blob/dbd5e1b274d30f9107141475eba116a8118bc346/packages/next/src/server/node-environment-extensions/random.tsx) to flag its use in static renders and force the user to make a choice between dynamically rendering a page/component (with random values) and caching the result of the call.

The usage here doesn't actually appear anywhere (it's entirely elided by the slice, right?) but it still triggers the error, which in development is just an annoying error popup but I'm not sure if it can be avoided (`"use cache"` requires an async function, whilst `await connection()` opts into dynamic rendering but that's not ideal to support a bundler hack...)

Are there any known alternatives for the Math.random here that achieve the same goal? Currently `dynamicIO` is an experimental flag, so it probably doesn't affect too many people, but I guess that fraction will grow over time (and the mechanism of flagging Math.random seems at least to me to be marginally more reasonable than using it to trick a bundler, although I don't know enough to suggest an alternative and recognise the need to avoid the 'optimization').

**Comment by bvaughn** [comment]
Realistically, I don't really have the time or energy to try to keep up with the stuff like this that the NextJS framework does. If someone else wants to do the legwork and tag me on a PR, I can try to make the time to review and release it. Otherwise it probably won't happen.
