### ISSUE TITLE
Conditional panel with collapsible panel issue

### ISSUE THREAD

**Issue by johnstack94** [bvaughn/react-resizable-panels#413]
Say we have three panels.

```
left, middle, right
```

* the left panel is collapsible to a size of 5%. 
* middle is static
* right panel is conditional

So basically toggling the right panel will expand the collapsed panel in this case:

```
1. left panel is collapsed
2. hiding right panel
```

The following image is when the left panel is collapsed and the right panel is visible.
![image](https://github.com/user-attachments/assets/a4a659fb-2173-4f12-828c-0a7f70ac168a)

however, when I hide the right panel I don't want the left panel to resize, since it causes it to not be collapsed anymore.

![image](https://github.com/user-attachments/assets/f5526a84-ffcf-46a9-a0b1-93aeb49bdca7)

**Comment by bvaughn** [comment]
I'm not sure what you mean by "the middle panel is static". This might be a bug but I'd need more than pictures to repro and look into fixing it, I think. Can you share _code_ (or even a failing unit test)?

**Comment by bvaughn** [comment]
For example if you've configured your panel group to auto-save panel layouts (`autoSaveId`) then it will remember layouts for each unique group of panels _individually_, in which case the behavior you're reporting is expected. (I know that design may be controversial, but it was intentional to support the use cases I had when developing this library).

**Comment by bvaughn** [comment]
(It's been a while since I wrote this part of the code, and I'm rusty on it.)

I believe this behavior is actually expected (regardless of the `autoSaveId` prop). There is not necessarily any meaningful relationship between two different groups of panels. For example, I could probably come up with scenarios where someone might want the _middle_ panel to retain its size in the scenario described above.

I think this library provides two options for you:
- Don't hide the right panel; just collapse it, OR
- Imperatively set the size of the collapsed panel to be collapsed again after hiding the right panel

**Comment by bvaughn** [comment]
What’s actually happening is this: Whenever the Panel group gets a new set of panels, it evaluates all of their constraints to figure out what the right default layout is.

When you switch from three panels, two panels, reruns this evaluation just as if the Panel group had originally mounted with only two panels.

I used to try to transition from one layout to the next, but there are too many cases and ambiguous behaviors to do that reliably I think.
