### ISSUE TITLE
Ability to keep dragging with mouse outside the window

### ISSUE THREAD

**Issue by NMinhNguyen** [bvaughn/react-resizable-panels#42]
If you compare https://codesandbox.io/s/react-resizable-panels-zf7hwd and https://react-grid-layout.github.io/react-grid-layout/ you'll notice that `react-grid-layout` lets you keep dragging even if your mouse leaves the window, but with `react-resizable-panels` the drag event seems to stop as soon as the mouse leaves the window.

This is probably not a dealbreaker, but it would arguably be nicer UX if the drag event didn't just stop if you accidentally dragged too much.

Sorry, I'm currently on my phone so I can't record a video to make it crystal clear what I'm talking about but I hope the description suffices!

**Comment by bvaughn** [comment]
The behavior of react-resizable-panels was intentional. I wanted to avoid the case of being stuck in a resize when you mouse up while outside of the window. I'm not sure if "mouseup" is guaranteed to always fire if the mouse has moved to another window.

Based on some quick testing though, it looks like Chrome, Firefox, and Safari all do a good job of handling this case (dispatching "mouseup" on the `window`) so maybe I can change this.

**Comment by bvaughn** [comment]
Resolved in #44

**Comment by bvaughn** [comment]
Released in v0.0.23
