### ISSUE TITLE
Direct control of sizes

### ISSUE THREAD

**Issue by shshaw** [bvaughn/react-resizable-panels#58]
Are there any ways to directly set the sizes for panels? On init, it seems like the `defaultSize` attribute for a Panel can do that but then there aren't any ways to override that later.

**Comment by bvaughn** [comment]
Not at present. What would be your use case?

In the past, I've found mixing "controlled" and "uncontrolled" APIs often leads to problems:
https://twitter.com/brian_d_vaughn/status/959600888242307072

**Comment by bvaughn** [comment]
1. _Saving/restoring sizes_ is possible with the current API. See [this demo page](https://react-resizable-panels.vercel.app/examples/external-persistence) which shows how to save/restore using the URL hash
2. _Minimizing/Maximizing Panels_ is not really possible with the current API in a satisfying way. You _could_ use the external persistence approach (above) and a React `key` to forcefully do it, but this would wipe out component state inside of the panel group which is not ideal.

**Comment by shshaw** [comment]
That sounds like a good approach.

What would be the right way to get the panel ref? Is it just passed along via `forwardRef`?

```
function MyPanel(){
  const panelRef = useRef();

  function maximize(){ 
    panelRef.current?.expand();
  }

  return (
    <Panel ref={panelRef}>
      <button onClick={maximize}>Maximize</button>
    </Panel>
  );
}
```

**Comment by bvaughn** [comment]
>  Is it just passed along via `forwardRef`?

I think I'd build it using `useImperativeHandle` but from a user's perspective that wouldn't be important– you'd just attach a `ref` to a `Panel` and use it.

**Comment by bvaughn** [comment]
Not finished _building_ the API yet (too tired to finish tonight) but this is how it will look.
https://react-resizable-panels-git-issues-58-bvaughn.vercel.app/examples/imperative-api

**Comment by bvaughn** [comment]
v0.0.29 just released

**Comment by josh-unwin** [comment]
Great solution, working well for me. Thanks a lot!

**Comment by bvaughn** [comment]
Happy to hear it!

**Comment by mohsinulhaq** [comment]
> In the past, I've found mixing "controlled" and "uncontrolled" APIs often leads to problems
Don't you think those problems might have arised because you were working with scrollTop and you had to handle scroll restoration and other related things.

Forgive me if I misunderstood, but in this case, with the size and collapse props, we are controlling only the CSS flex property of the panels, which can be easily controllable without worrying about re-applying the current values like we had to with scrollTop value.

**Comment by bvaughn** [comment]
> Don't you think those problems might have arised because you were working with scrollTop and you had to handle scroll restoration and other related things.

I think it's a question of control/responsibility. If two separate pieces of code are changing the same value– what happens if they conflict? The result is unpredictable– the last one in "wins".

I _could_ provide both interfaces– and follow `react-dom` pattern of  warning if e.g. an "uncontrolled" input (`value` is `undefined`) becomes "controlled", and/or if you provide a `value` without an `onChange` handler, but that adds a lot of complexity to this package, because it now needs to support two distinct modes.

I guess it comes down to... I don't want to support this functionality 😄
