### ISSUE TITLE
external-persistence URL hash hinders history

### ISSUE THREAD

**Issue by tomByrer** [bvaughn/react-resizable-panels#68]
1. [External persistence](https://react-resizable-panels.vercel.app/examples/external-persistence)
2. resize a panel or 2
3. try to go back in history
4. feel like you're starting an idle game ;)

Seems a new URL hash is written on every mouse move, which makes for a long history history.

Suggested fixes:
1. debounce would reduce the number of updates
2. wait for a mouseup (or timer for keyboard control) to change the URL hash.

I guess you might have excessive `localStorage` writes also, but didn't test for it.

---

Thanks for this project; I bookmarked for usage later, & I'm sure many other folks will use in their projects!

**Comment by bvaughn** [comment]
Not super concerned about the URL/history issue 😅 since it’s just a demo (and there’s a “back” link on the page) but your point about thrashing local storage is a good one. Debouncing the updates would probably be a good change. (Might also just never update during a drag- waiting until the drag finishes.)

**Comment by bvaughn** [comment]
I believe #69 should resolve this issue

**Comment by bvaughn** [comment]
Released as v0.0.30

**Comment by bvaughn** [comment]
Thank you for the suggestion and the kind words!
