### ISSUE TITLE
Providing access to current size using the imperative API

### ISSUE THREAD

**Issue by nksaraf** [bvaughn/react-resizable-panels#77]
Can the imperative API provide a function like `getSize` to get the current size. this way we can have logic that can position and size stuff with absolute positioning but aware of the panel sizes.

**Comment by bvaughn** [comment]
Check out the docs:
https://github.com/bvaughn/react-resizable-panels/tree/main/packages/react-resizable-panels#panel

There is a `getSize` method on the Panel API provided you're using [v0.0.31](https://github.com/bvaughn/react-resizable-panels/blob/main/packages/react-resizable-panels/CHANGELOG.md#0031) or newer.

Note though that it returns the _percentage_ size (1-100) rather than the _pixel_ size. If you want the latter, you'll have to do the conversion.
