### ISSUE TITLE
Issue in Order props in Panel

### ISSUE THREAD

**Issue by sbaz44** [bvaughn/react-resizable-panels#79]
Hi. I forked your codesandbox repo and tried creating my panels using your documentation.
The issue is that when I tried resizing **1** and **2** block it flickers and adjusts automatically.

Codesandbox Link - [https://codesandbox.io/s/react-resizable-panels-forked-7ch71r?file=/src/App.js](https://codesandbox.io/s/react-resizable-panels-forked-7ch71r?file=/src/App.js)

Can someone please help me out what I am doing wrong here or is it a bug?

Thank You.

**Comment by bvaughn** [comment]
Your sandbox has two issues:
* It's initializing both `Panel`s in the top `PanelGroup` to default size of 20%. 20% + 20% = 40% rather than 100%, which starts `PanelGroup` off in an invalid state that it doesn't handle well. I created #65 to add a warning for cases like this but haven't had time to implement it yet.
* It's using the same `autoSaveId` prop for both `PanelGroup`s which may cause them to interfere with each other.

Here's a forked and fixed version of your sandbox:
https://codesandbox.io/s/react-resizable-panels-forked-lwmgqo?file=/src/App.js
