### ISSUE TITLE
A way to derive dragging active state

### ISSUE THREAD

**Issue by antonisierakowski** [bvaughn/react-resizable-panels#94]
My specific use case requires me to disable certain app features and hide a few elements while the user is dragging a panel handle to save up on performance, so I need to be able to somehow derive this dragging active state using the library API.
In the library I was going to migrate from I could just pass callbacks that were called whenever the user started or stopped dragging the handles (something like `onResizeStart`/`onResizeEnd`).

**Comment by bvaughn** [comment]
What’s your motivation for switching away from the library you’re currently using?

**Comment by antonisierakowski** [comment]
To be clear, what I referred to as 'library' is a set of class-based, non-typescript components that were originally ripped from an actual library and commited into the codebase I'm currently contributing to (after making some unspecified adjustments to meet the requirements). I'm looking to replace it as it's a general mess and a nightmare to maintain.

**Comment by bvaughn** [comment]
I think `PanelGroup` could probably be updated to support an optional start/stop callback prop (not sure about what they'd be named) that could be called from these two places:
https://github.com/bvaughn/react-resizable-panels/blob/dffc160ecf9c917701f3eec043629736b5e2eb8d/packages/react-resizable-panels/src/PanelGroup.ts#L589C7-L607

Note that I don't think it makes senes to try to fire that event for Window Splitter events (resizing by keyboard) because there's no explicit _stop_ for those, nor for imperative resize methods (by React refs) because those are generally discrete– only for resizes done by pointer.

**Comment by bvaughn** [comment]
Available in v0.0.37
